[package]
name = "dioxus-tui"
version = "0.5.0-alpha.2"
authors = ["Jonathan Kelley, Evan Almloff"]
edition = "2021"
description = "TUI-based renderer for Dioxus"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.7/getting_started/tui"
keywords = ["dom", "ui", "gui", "react", "terminal"]
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = { version = "0.7.1" }
dioxus-core = { version = "0.7.1", features = ["serialize"] }
dioxus-html = { version = "0.7.1" }
dioxus-core-types = "0.7.1"
keyboard-types = "0.7"
smallvec = "1.6"
anymap3 = "1.0.1"
parking_lot = { version = "0.12.1", features = ["send_guard"] }
dashmap = "5.4.0"
dioxus-native-core-macro = "0.5.0-alpha.0"
lightningcss = "1.0.0-alpha.39"
dioxus-hot-reload = { version = "0.6.0-alpha.2", optional = true }

crossterm = "0.26.1"
tokio = { version = "1.36", features = ["full"] }
futures = "0.3.30"
futures-channel = "0.3.30"
taffy = "0.3.12"
shipyard = { version = "0.6.2", features = ["proc", "std"], default-features = false }
once_cell = "1.17.1"
rustc-hash = "1.1.0"
ratatui = "0.24.0"
anyhow = "1.0.42"

[dev-dependencies]
tokio = { version = "1.36", features = ["full"] }
criterion = "0.3.5"

[[bench]]
name = "update"
harness = false

[features]
default = []
hot-reload = ["dioxus-hot-reload"]
