[package]
name = "dioxus-tui"
version = "0.7.1"
authors = ["Jonathan Kelley, Evan Almloff"]
edition = "2021"
description = "TUI-based renderer for Dioxus"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.7/getting_started/tui"
keywords = ["dom", "ui", "gui", "react", "terminal"]
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = { version = "0.7.1" }
dioxus-core = { version = "0.7.1", features = ["serialize"] }
dioxus-html = { version = "0.7.1" }
dioxus-core-types = "0.7.1"
keyboard-types = "0.7"
dioxus-hot-reload = { version = "0.6.0-alpha.2", optional = true }
dioxus-native = { version = "0.7.1", optional = true }

tokio = { version = "1.36", features = ["full"] }
futures = "0.3.30"
futures-channel = "0.3.30"
termwiz = "0.22"
unicode-width = "0.1"
anyhow = "1.0.42"
bevy_ecs = { version = "0.11", default-features = false }
blitz-dom = { version = "0.2.2", default-features = false, features = ["system_fonts"] }
blitz-traits = { version = "0.2.0" }
blitz-paint = { version = "0.2.1", default-features = false, optional = true }
dioxus-native-dom = "0.7.1"
anyrender = "0.6"
anyrender_vello_cpu = { version = "0.8.1", optional = true }
png = "0.17"
base64 = "0.22"
peniko = "0.5"
kurbo = "0.12"
ttf-parser = "0.19"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "ansi"] }
thiserror = "1"
style = { version = "0.8", package = "stylo" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
dioxus = { version = "0.7.1" }
tokio = { version = "1.36", features = ["full"] }
criterion = "0.8.0"
clap = { version = "4.5", features = ["derive"] }

[[bench]]
name = "update"
harness = false

[features]
default = []
hot-reload = ["dioxus-hot-reload"]
blitz = ["dep:blitz-paint", "dep:anyrender_vello_cpu", "dep:dioxus-native"]

# Backwards-compatible aliases.
blitz-terminal = ["blitz"]
blitz-gui = ["blitz"]
