[package]
name = "dioxus-tui-components"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = { version = "0.7.2" }
dioxus-html = { version = "0.7.2" }
dioxus-tui = { path = ".." }

[dev-dependencies]
dioxus-core = { version = "0.7.2" }
dioxus-native-dom = "0.7.2"
blitz-dom = { version = "0.2.2", default-features = false, features = ["system_fonts"] }
blitz-traits = { version = "0.2.0" }
termwiz = "0.23"
